version: 2

sources:
  - name: retail
    description: A jaffle shop data source
    database: dbt_database
    tables:
      - name: dim_customers
      - name: dim_products
      - name: dim_stores
      - name: dim_time
      - name: dim_employees
      - name: fact_sales
      - name: fact_inventory